apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: futi-api
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/client-name: "gcloud"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/futi-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgresql://USER:PASSWORD@HOST:6543/postgres?pgbouncer=true"
            - name: DIRECT_URL
              value: "postgresql://USER:PASSWORD@HOST:5432/postgres"
            - name: FIREBASE_PROJECT_ID
              value: "your-firebase-project-id"
            - name: FIREBASE_CLIENT_EMAIL
              value: "firebase-adminsdk@your-project.iam.gserviceaccount.com"
            - name: FIREBASE_PRIVATE_KEY
              value: "-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          # If using Cloud SQL Proxy sidecar, you'd add it here. For PlanetScale, not required.
      timeoutSeconds: 300
